name    'erwbgy-wso2'
version '0.2.0'
source 'https://github.com/erwbgy/puppet-wso2.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Install and run WSO2 products'
description 'Install and run WSO2 products'
project_page 'git.com:erwbgy/puppet-wso2.git'
dependency 'erwbgy/runit', '>= 0.2.0'
